//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshBoutique.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ChildCategories = new HashSet<Category>();
            this.Articles = new HashSet<Article>();
        }
    
        public int Id { get; set; }
        public string UrlName { get; set; }
        public string Title { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public int OrderIndex { get; set; }
    
        public virtual ICollection<Category> ChildCategories { get; set; }
        public virtual Category ParentCategory { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
