//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshBoutique.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderStatusesHistory = new HashSet<OrderStatusesHistory>();
        }
    
        public int Id { get; set; }
        public string DeliveryMerchant { get; set; }
        public decimal DeliveryPrice { get; set; }
        public bool HasCommission { get; set; }
        public double CommissionPercents { get; set; }
        public decimal ShippingPrice { get; set; }
        public decimal ItemsPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public System.Guid UserId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int PaymentMethodId { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual ICollection<OrderStatusesHistory> OrderStatusesHistory { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
