//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshBoutique.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeType
    {
        public SizeType()
        {
            this.Articles = new HashSet<Article>();
            this.Sizes = new HashSet<Size>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Size> Sizes { get; set; }
    }
}
